# Generated by Django 4.2.1 on 2023-05-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="People",
            new_name="Member",
        ),
        migrations.RenameField(
            model_name="club",
            old_name="poeples",
            new_name="members",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="people",
            new_name="member",
        ),
    ]
